### ISSUE TITLE
 Permission denied

### ISSUE THREAD

**Issue by hiqmatNisa** [omni-us/research-seq2seq-HTR#4]
Hi,
First of all thank you for sharing this code with us. 
I am facing a  Permission denied error while executing shell file ./tasas_cer.sh in a main_torch_latest.py in a line 312. 
res_cer = sub.Popen(['./tasas_cer.sh', gt, decoded], stdout=sub.PIPE) 

I also add  shell=True but got the same error again. 
I also tried to change the permission of that file by executing python command 
os.chmod('tasas_cer.sh', stat.S_IXOTH)
but unfortunately I got the same error again. 
I am running this code on google colab. 
Can you help me out please?

**Comment by Gaber-Youssef** [comment]
I fix it by this:
before you start training, write in the terminal (or in the jupyter notebook cell after adding '!' at the beginning of the line)

> chmod +x run_train.sh tasas_cer.sh run_test.sh tasas_wer.sh utils/tasas utils/htrsh.inc.sh utils/run_parallel.inc.sh test.sh

**Comment by hiqmatNisa** [comment]
> I fix it by this:
> before you start training, write in the terminal (or in the jupyter notebook cell after adding '!' at the beginning of the line)
> 
> > chmod +x run_train.sh tasas_cer.sh run_test.sh tasas_wer.sh utils/tasas utils/htrsh.inc.sh utils/run_parallel.inc.sh test.sh

Thank you so much. It works for me. Before that I have run below command for every .sh file. and  it works too. 
os.chmod("tasas_cer.sh", stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR |stat.S_IWUSR)
